### ISSUE TITLE
Symbol’s function definition is void: facemenu-add-face

### ISSUE THREAD

**Issue by oatmealm** [lorniu/go-translate#11]
Hi,

I'm now getting this error most times when trying to translate strings:

```
error in process filter: go-translate-default-buffer-render: Symbol’s function definition is void: facemenu-add-face
error in process filter: Symbol’s function definition is void: facemenu-add-face
```

I've recently switched to emacs-pgtk-nativecomp (`GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.28, cairo version 1.16.0) of 2021-04-02
`) but it did work well until today... so not sure if related at all.

**Comment by lorniu** [comment]
Maybe you should add `(require 'facemenu)` to your init file.

**Comment by oatmealm** [comment]
> Maybe you should add `(require 'facemenu)` to your init file.

Any idea why it's not loading? I didn't have to do that so far (Doom Emacs) and the only change is moving to the nativecomp branch....
