### ISSUE TITLE
Dependency on posframe

### ISSUE THREAD

**Issue by otech-nl** [lorniu/go-translate#14]
Hello,

I am trying out this package. Thank you for your work :)

While playing around, I noticed that you need to install 
https://github.com/tumashu/posframe
to get the `popup` commands working.

**Comment by lorniu** [comment]
I provide the command `go-translate-popup` just as a sample, you can create yours like this.
This command depends on `posframe` just for convenience.
I think it is a bad idea to let this package explicitly depend on `posframe`.

So, if you like this command, you can:
1. install `posframe` and make sure it is in your load-path
2. compose your own popup command yourself just like code showing in `go-translate-popup`

And maybe we can rewrite `go-translate-popup` with child-frame API. Any idea, please post a PR.

**Comment by otech-nl** [comment]
Thanks for your response.
