### ISSUE TITLE
 connection-failed ，failed with code 110

### ISSUE THREAD

**Issue by e190** [lorniu/go-translate#17]
怎么translate.google.cn突然不能使用了？
我用浏览器都能翻译，应该不是网站的问题
在emacs里面也能 连上这个网站，就是翻译不了。
能看看是什么问题吗？

Debugger entered--Lisp error: (wrong-type-argument sequencep 82)
  mapconcat(#f(compiled-function (item) #<bytecode 0x1588630e0e6d>) 82 "")
  go-translate-result--translation("Request Error: ((error connection-failed failed wi...")
  #f(compiled-function (req resp) #<bytecode 0x158862f138e5>)(("https://translate.google.cn/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&..." #(";; Change the variable values and key bindings to ..." 0 59 (follow t)) "en" "zh-CN") "Request Error: ((error connection-failed failed wi...")
  #f(compiled-function (status) #<bytecode 0x158862cf9f09>)((:error (error connection-failed "failed with code 110\n" :host "translate.google.com" :service 443) :redirect "https://translate.google.com/translate_a/single?cl..." :peer (:certificates ((:version 3 :serial-number "00:e8:eb:65:79:83:1b:ba:e0:0a:00:00:00:00:fc:f9:dc" :issuer "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :valid-from "2021-08-30" :valid-to "2021-11-22" :subject "CN=*.google.cn" :public-key-algorithm "EC/ECDSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:a5:19:50:3e:18:42:3c:9b:d3:86:80:57:f2:8b:9f:..." :certificate-id "sha1:75:a1:4d:5f:3e:94:d4:47:39:47:b7:37:b1:32:55:..." :pem "-----BEGIN CERTIFICATE-----\nMIIEjjCCA3agAwIBAgIRAO...") (:version 3 :serial-number "02:03:bc:53:59:6b:34:c7:18:f5:01:50:66" :issuer "C=US,O=Google Trust Services LLC,CN=GTS Root R1" :valid-from "2020-08-13" :valid-to "2027-09-30" :subject "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:34:69:bb:fa:7c:26:15:12:8d:8d:9b:d6:1e:b3:14:..." :certificate-id "sha1:1e:7e:f6:47:cb:a1:50:28:1c:60:89:72:57:10:28:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFljCCA36gAwIBAgINAg...") (:version 3 :serial-number "77:bd:0d:6c:db:36:f9:1a:ea:21:0f:c4:f0:58:d3:0d" :issuer "C=BE,O=GlobalSign nv-sa,OU=Root CA,CN=GlobalSign R..." :valid-from "2020-06-19" :valid-to "2028-01-28" :subject "C=US,O=Google Trust Services LLC,CN=GTS Root R1" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:85:56:53:49:be:ea:4a:b1:86:49:b5:61:71:a9:95:..." :certificate-id "sha1:08:74:54:87:e8:91:c1:9e:30:78:c1:f2:a0:7e:45:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFYjCCBEqgAwIBAgIQd7...")) :certificate (:version 3 :serial-number "00:e8:eb:65:79:83:1b:ba:e0:0a:00:00:00:00:fc:f9:dc" :issuer "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :valid-from "2021-08-30" :valid-to "2021-11-22" :subject "CN=*.google.cn" :public-key-algorithm "EC/ECDSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:a5:19:50:3e:18:42:3c:9b:d3:86:80:57:f2:8b:9f:..." :certificate-id "sha1:75:a1:4d:5f:3e:94:d4:47:39:47:b7:37:b1:32:55:..." :pem "-----BEGIN CERTIFICATE-----\nMIIEjjCCA3agAwIBAgIRAO...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)))
  apply(#f(compiled-function (status) #<bytecode 0x158862cf9f09>) (:error (error connection-failed "failed with code 110\n" :host "translate.google.com" :service 443) :redirect "https://translate.google.com/translate_a/single?cl..." :peer (:certificates ((:version 3 :serial-number "00:e8:eb:65:79:83:1b:ba:e0:0a:00:00:00:00:fc:f9:dc" :issuer "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :valid-from "2021-08-30" :valid-to "2021-11-22" :subject "CN=*.google.cn" :public-key-algorithm "EC/ECDSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:a5:19:50:3e:18:42:3c:9b:d3:86:80:57:f2:8b:9f:..." :certificate-id "sha1:75:a1:4d:5f:3e:94:d4:47:39:47:b7:37:b1:32:55:..." :pem "-----BEGIN CERTIFICATE-----\nMIIEjjCCA3agAwIBAgIRAO...") (:version 3 :serial-number "02:03:bc:53:59:6b:34:c7:18:f5:01:50:66" :issuer "C=US,O=Google Trust Services LLC,CN=GTS Root R1" :valid-from "2020-08-13" :valid-to "2027-09-30" :subject "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:34:69:bb:fa:7c:26:15:12:8d:8d:9b:d6:1e:b3:14:..." :certificate-id "sha1:1e:7e:f6:47:cb:a1:50:28:1c:60:89:72:57:10:28:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFljCCA36gAwIBAgINAg...") (:version 3 :serial-number "77:bd:0d:6c:db:36:f9:1a:ea:21:0f:c4:f0:58:d3:0d" :issuer "C=BE,O=GlobalSign nv-sa,OU=Root CA,CN=GlobalSign R..." :valid-from "2020-06-19" :valid-to "2028-01-28" :subject "C=US,O=Google Trust Services LLC,CN=GTS Root R1" :public-key-algorithm "RSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:85:56:53:49:be:ea:4a:b1:86:49:b5:61:71:a9:95:..." :certificate-id "sha1:08:74:54:87:e8:91:c1:9e:30:78:c1:f2:a0:7e:45:..." :pem "-----BEGIN CERTIFICATE-----\nMIIFYjCCBEqgAwIBAgIQd7...")) :certificate (:version 3 :serial-number "00:e8:eb:65:79:83:1b:ba:e0:0a:00:00:00:00:fc:f9:dc" :issuer "C=US,O=Google Trust Services LLC,CN=GTS CA 1C3" :valid-from "2021-08-30" :valid-to "2021-11-22" :subject "CN=*.google.cn" :public-key-algorithm "EC/ECDSA" :certificate-security-level "High" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:a5:19:50:3e:18:42:3c:9b:d3:86:80:57:f2:8b:9f:..." :certificate-id "sha1:75:a1:4d:5f:3e:94:d4:47:39:47:b7:37:b1:32:55:..." :pem "-----BEGIN CERTIFICATE-----\nMIIEjjCCA3agAwIBAgIRAO...") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD" :encrypt-then-mac nil)))
  url-http-activate-callback()
  url-http-async-sentinel(#<process translate.google.com<3>> "failed with code 110\n"

**Comment by lorniu** [comment]
translate.google.cn  的 API 变了,请求的时候被重定向到了 translate.google.com,因此可能需要挂代理才能访问.

页面版的 translate.google.cn 使用了不同的 API.

**Comment by e190** [comment]
那怎么办？你这边有将 新API 更新上去的计划吗？

**Comment by lorniu** [comment]
目前挂代理可用.

后面有时间会更新上去.现在比较忙,没时间研究.
