### ISSUE TITLE
gts-kill-ring-render saves both input & output

### ISSUE THREAD

**Issue by strikerlulu** [lorniu/go-translate#20]
In v1 i think `go-translate-kill-ring-save` only saved the output(target lang)
but now `gts-kill-ring-render` saves both input & output
I see an option to create my own render but how do i just get the result of translated text from `result` ?

**Comment by lorniu** [comment]
Same keybinds as in `gts-buffer-render`. Focus and click the pop-up frame window, and then use `y` to play the sound.

**Comment by strikerlulu** [comment]
i don't wanna use mouse :(
so i think I've to create a new parser and use `go-tts` function to speak
```elisp
;; A method
(cl-defmethod gts-out ((_ your-render) result)
  (deactivate-mark)
  (insert result))
  ```
  and in the README instead `result` shouldn't it be `task` ? how do i get the insert-able text from the `task` ?

**Comment by strikerlulu** [comment]
Ah got it...
can i make the `gts-tts` async ?
```elisp
  (cl-defmethod gts-out ((_ gts-posframe-pop-render) task)
    (when-let ((buf (gts-render-buffer gts-posframe-pop-render-buffer task)))
      (posframe-refresh buf)
      (add-hook 'post-command-hook #'gts-posframe-render-auto-close-handler))
      (with-slots (text from engine) task
        (gts-tts (gts-google-engine) text from)))
```
and i think in README it should be
```elisp
(cl-defmethod gts-out ((_ your-render) task)
  (deactivate-mark)
  (with-slots (result) task
    (insert result)))
```

**Comment by lorniu** [comment]
Thanks for correcting.

And, with `eieio` you can write shorter:
```elisp
(cl-defmethod gts-out :after ((_ gts-posframe-pop-render) task)
  (with-slots (text from engine) task
    (gts-tts engine text from)))
```
