### ISSUE TITLE
Translate direction option?

### ISSUE THREAD

**Issue by brogowski** [lorniu/go-translate#32]
Hi,

I'm trying to write small function to get translation show up in minibuffer.

```lisp
(use-package go-translate
  :custom
  (gts-translate-list '(("pl" "en"))))

(defun my/go-translate-at-point ()
  (interactive)
  (gts-translate (gts-translator
                  :picker (gts-noprompt-picker)
                  :engines (gts-google-engine)
                  :render (gts-message-render))))

(defclass gts-message-render (gts-render) ())

(cl-defmethod gts-out ((_ gts-message-render) task)
  (deactivate-mark)
  (with-slots (result ecode) task
    (if ecode
        (user-error "%s" result)
      (message (nth 0 (split-string result "\n"))))))
```

However it looks like language pairs are ordered alphabetically...
I'm getting translation from "en" to "pl" instead of "pl" to "en".

Is there any way I can specify translate direction?

**Comment by brogowski** [comment]
Hmm, on the other hand function with `gts-prompt-picker` works only in reverse - asking always for "pl" to "en" translation.

```lisp
(defun my/go-translate ()
  (interactive)
  (gts-translate (gts-translator
                  :picker (gts-prompt-picker)
                  :engines (gts-google-engine)
                  :render (gts-buffer-render))))
```

**Comment by lorniu** [comment]
The current picker mainly relies on 'gts-picker-lang-match-alist' for language judgment.

I'm not familiar with `pl`, but you can add your rule by adding:
```elisp
(add-to-list gts-picker-lang-match-alist (cons "pl" "[regexp to judge whether current input is pl]"))
```

Of course, this mechanism of automatic judgment is not a panacea, because some languages are really difficult to distinguish.

Then, you can:

1. use `x` in the result buffer to switch back

2. customize your own `pick path logic`:

   ```elisp
   (defmethod gts-path ((o gts-prompt-picker) text)
      ;; return a proper path for your own
      )
   ```

Or, you can try to provide PR to make the auto judgment more perfect.

**Comment by brogowski** [comment]
Thanks @lorniu - I've added simple regex for `pl` (it's latin based).
```lisp
(add-to-list 'gts-picker-lang-match-alist
                   (cons "pl" "^[a-zA-Z\u0105-\u017b,.;_ ]+$"))
```
and now it starts with translation from `pl` to `en`.

However, I don't think that's going to be useful for you since it is overriding `en` regex.

**Comment by walseb** [comment]
For context, here is the relevant code:
```
(gts-translate (gts-translator
                  :picker (gts-noprompt-picker :texter (my/gts-string-texter))
                  :engines (gts-bing-engine)
                  :render (my/gts-insert-render)
                  :path lang ;; (cons "en" "sv") or (cons "sv" "en")
                  ))
```
