### ISSUE TITLE
(gts-buffer-render) - parameter to create the translate buffer below versus on the side?

### ISSUE THREAD

**Issue by thjwong** [lorniu/go-translate#39]
Thanks for creating go-translate! I've been using the other package google-translate before :)

Is there any parameter I can pass to (gts-buffer-render) in the : render section of gts-default-translator? So that the translation buffer will be created by choice on the side (like right now) or below (like doing a C-x 2)?

It's more like a feature suggestion than a real "issue". Thanks!

**Comment by lorniu** [comment]
Use `gts-buffer-window-config` to custom the buffer display behavior, see `C-h v gts-buffer-window-config` for more.
