### ISSUE TITLE
gts-buffer-render 显示结果。在结果窗口不能使用快捷键

### ISSUE THREAD

**Issue by ibytao** [lorniu/go-translate#47]
在结果窗口使用快捷键没有任何反映

**Comment by lorniu** [comment]
能描述详细点吗？我两台电脑，一台 Windows 一台 Linux，分别是 emacs28 和 emacs29，都没发现快捷键有问题。

麻烦提供你的环境、版本以及配置?

**Comment by ibytao** [comment]
电脑是mac min 2018  emacs29
