### ISSUE TITLE
Can't access the items beyond #2 items in the gts-translate-list 

### ISSUE THREAD

**Issue by thjwong** [lorniu/go-translate#50]
For example, if the gts-translate is set like this:

`(setq gts-translate-list '(("de" "en")("en" "de")("en" "it")("it" "en")))`

then c-N and c-P can only access up to ` ("en" "de")` and further pressing c-N will change the translation path back to `("de" "en")`

**Comment by lorniu** [comment]
I don't quite understand what you mean. Can you show your configuration about `go-translate` and paste some text you want to translate here?

**Comment by gyps** [comment]
I seem to have the same issue. My config is simply:
```
(setq gts-translate-list '(("de" "en") ("de" "it")))
(setq gts-default-translator
      (gts-translator
       :picker (gts-prompt-picker)
       :engines (list (gts-google-engine))
       :render (gts-buffer-render)))
```
pressing `x` or `M-n`/`M-p` toggles between en->de and de->en but how can I access the second option to translate de<->it ?

Cheers,
Alex

**Comment by lorniu** [comment]
Fixed, please have a try.

**Comment by gyps** [comment]
Works like a charm. Thanks!
