### ISSUE TITLE
关于终端下的使用

### ISSUE THREAD

**Issue by bommbo** [lorniu/go-translate#53]
抱歉麻烦您测试下，我自己没办法在终端下使用这个包，但是在GUI下能使用，但是终端下无法使用，一直显示 using a proxy for http / using a  proxy for https ，但其实我在终端下也用了类似 export http_proxy= 的方式。

**Comment by lorniu** [comment]
我的Archlinux 终端和GUI下都正常。

是不是你的代理有问题？首先你把代理取消掉看看有没有问题。或者可以通过 proxychains 之类的设置下代理试试？

另外 emacs 内部可以使用 `url-proxy-services` 配置 url-retrieve 的代理。

**Comment by bommbo** [comment]
谢谢啊，应该是代理，最近bing好像出问题，切到google才发现这个问题。

**Comment by bommbo** [comment]
还是不行，zsh 下的export HTTPS_PROXY=http://127.0.0.1:1087，vim 下的翻译工具切到google，翻译正常。
emacs下的两种方式：
(setq url-gateway-method 'socks)
(setq socks-server '("Default server" "127.0.0.1" 1080 5))

(setq url-proxy-services '(("http" . "127.0.0.1:1087")))
GUI下都能正常翻译，但是终端下就是无法翻译。求换个代理方式，我已经试过好多次了，就是不行，proxychains干脆直接干扰emacs文本，直接乱码

**Comment by lorniu** [comment]
posframe 是不是不能在终端下面使用？你换成 gts-buffer-render 看看能行吗？另外如果有错误，麻烦你把错误的文本发来看看？

另外，proxychains 让 emacs 乱码？没道理啊。

**Comment by bommbo** [comment]
确定了，真不会弹窗，翻译正常。另外 proxychains真的会让它乱码。
用acm-terminal 使lsp-bridge,都恍惚了，觉得终端下emacs弹窗应该是有实现的，抱歉抱歉。

![image](https://user-images.githubusercontent.com/61496351/217984487-268f091f-5d95-444d-a48f-83487cd4d368.png)
