### ISSUE TITLE
Possibly accidential history rewrite

### ISSUE THREAD

**Issue by tarsius** [lorniu/go-translate#56]
Are you aware that you have rewritten all history since `v0.1`? One consequence of that is that later tags are no longer reachable from a branch.

Same for `ox-spectacle`.

Ah, I see. You changed your email. You usually shouldn't rewrite history for that. And you don't have to; you could instead add `.mailmap`. See https://git-scm.com/docs/gitmailmap.

**Comment by lorniu** [comment]
Oh, sorry, I just want to correct my massy email addresses. Thanks for the reminder.

**Comment by tarsius** [comment]
Are you going to revert the rewrite or stick to it? Either one is fine, but if you tell me, I can avoid having to twice intervene manually when updating these packages on the [Emacsmirror](https://github.com/emacsmirror). If you stick to the rewrite, then you should also update the tags.

**Comment by lorniu** [comment]
I have updated the tags. Stick to the rewrite please.

**Comment by tarsius** [comment]
Thanks!

**Comment by tarsius** [comment]
> I have updated the tags.

I think you forgot to (force) push them.

**Comment by lorniu** [comment]
Isn't that push like this?
```
git push origin --tags --force
```

I haved pushed like that and tag links in github is reachable (for example: [v0.4](https://github.com/lorniu/go-translate/releases/tag/v0.4)).

**Comment by tarsius** [comment]
Yes, the tags are there.
Sorry for the noise.
