### ISSUE TITLE
Invalid slot name

### ISSUE THREAD

**Issue by OrionRandD** [lorniu/go-translate#62]
;; In Doom-Emacs, this line:

;; (gts-google-rpc-engine :parser (gts-google-rpc-parser) :url "https://translate.google.com")

;; is getting this error:

;; Invalid slot name: "#<gts-google-rpc-engine gts-google-rpc-engine-1583d9a75f30>", :url

This  is the debug message:

Debugger entered--Lisp error: (invalid-slot-name "#<gts-google-rpc-engine gts-google-rpc-engine-1583..." :url)
  signal(invalid-slot-name ("#<gts-google-rpc-engine gts-google-rpc-engine-1583..." :url))
  #f(compiled-function (object slot-name operation &optional new-value) #<bytecode 0x981ad1b01a1b321>)(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> :url oset "https://translate.google.com")
  apply(#f(compiled-function (object slot-name operation &optional new-value) #<bytecode 0x981ad1b01a1b321>) #<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:url oset "https://translate.google.com"))
  slot-missing(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> :url oset "https://translate.google.com")
  #f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode 0xc40095489ed7e5e>)(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  apply(#f(compiled-function (obj slots) "Set slots of OBJ with SLOTS which is a list of name/value pairs.\nCalled from the constructor routine." #<bytecode 0xc40095489ed7e5e>) #<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  shared-initialize(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  #f(compiled-function (this &optional args) "Construct the new object THIS based on ARGS.\nARGS is a property list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from ARGS." #<bytecode -0xba8fccbe71c2c47>)(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  apply(#f(compiled-function (this &optional args) "Construct the new object THIS based on ARGS.\nARGS is a property list where odd numbered elements are tags, and\neven numbered elements are the values to store in the tagged slot.\nIf you overload the `initialize-instance', there you will need to\ncall `shared-initialize' yourself, or you can call `call-next-method'\nto have this constructor called automatically.  If these steps are\nnot taken, then new objects of your class will not have their values\ndynamically set from ARGS." #<bytecode -0xba8fccbe71c2c47>) #<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  initialize-instance(#<gts-google-rpc-engine gts-google-rpc-engine-1583da056f58> (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x1de2701c3bb28ab3>)(gts-google-rpc-engine :parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x1de2701c3bb28ab3>) gts-google-rpc-engine (:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com"))
  make-instance(gts-google-rpc-engine :parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com")
  gts-google-rpc-engine(:parser #<gts-google-rpc-parser gts-google-rpc-parser-1583d9383fa6> :url "https://translate.google.com")
  (list (gts-bing-engine) (gts-google-engine :parser (gts-google-summary-parser)) (gts-google-rpc-engine :parser (gts-google-rpc-parser) :url "https://translate.google.com"))
  (progn (list (gts-bing-engine) (gts-google-engine :parser (gts-google-summary-parser)) (gts-google-rpc-engine :parser (gts-google-rpc-parser) :url "https://translate.google.com")))
  elisp--eval-last-sexp(nil)
  #<subr eval-last-sexp>(nil)
  apply(#<subr eval-last-sexp> nil)
  eval-last-sexp(nil)
  eros-eval-last-sexp(nil)
  funcall-interactively(eros-eval-last-sexp nil)
  command-execute(eros-eval-last-sexp)

**Comment by lorniu** [comment]
There is no `:url` slot in `gts-google-rpc-engine`, use `gts-google-rpc-base-url` instead if necessary:
```elisp
(setq gts-google-rpc-base-url "https://translate.google.com")
```
