### ISSUE TITLE
[Feature] make gt-posframe-pop-render frame customizable

### ISSUE THREAD

**Issue by seagle0128** [lorniu/go-translate#69]
Now gt-posframe-pop-render frame is not customizable for frame parameters, e.g. border. I'd like make it like below. 

I can make a PR if you will.

![image](https://github.com/lorniu/go-translate/assets/140797/9729fd5c-8c20-4d95-ad25-d09b8a2d8a3a)

**Comment by lorniu** [comment]
Do the commit in the `improve-posframe-render` branch meet the needs? Suggestions please.

Usage example:
```elisp
(gt-posframe-pin-render :extra-params (list :border-width 40 :border-color "red"))
```

**Comment by seagle0128** [comment]
> Do the commit in the `improve-posframe-render` branch meet the needs? Suggestions please.

The branch did work well for me.

**Comment by lorniu** [comment]
Merged. The slot is renamed to `frame-params`.

**Comment by seagle0128** [comment]
It seems it hasn't been released to melpa yet.
