### ISSUE TITLE
Error when fetching Token-Key

### ISSUE THREAD

**Issue by oatmealm** [lorniu/go-translate#7]
Hi. Thanks a lot for this mode, vert helpful and thought out!

Iv'e noticed recently I'm getting this all the time... I'm not sure why.

```
user-error: Error when fetching Token-Key. Check your network and proxy, or retry later
```

**Comment by mackong** [comment]
Same issue here, both *https://translate.google.com* and *https://translate.google.cn*.

**Comment by lorniu** [comment]
see #8

**Comment by oatmealm** [comment]
Sorry. I didn't see this issue first. Solved!
