### ISSUE TITLE
[Feature] Translation using (Local) LLM

### ISSUE THREAD

**Issue by hwiorn** [lorniu/go-translate#74]
`go-translate` already has ChatGPT implementation.

So, I think go-translate interface can be extended by implementing LLM feature such as [ellama-translate](https://github.com/s-kostyaev/ellama?tab=readme-ov-file#ellama-translate)(using https://github.com/ahyatt/llm) or [gptel](https://github.com/karthink/gptel) packages.

How do you think?

**Comment by lorniu** [comment]
That's what's going on in the  [chat](https://github.com/lorniu/go-translate/tree/chat) branch. The branch is not complete yet.

Currently, it only supports ChatGPT, and the functionality is not complete enough, and the interaction logic isn't very satisfying yet. I need to spend time improving and optimizing it.

If you just chat based on ChatGPT, it already works very well. I use it every day now.

The next step is:
- complete ChatGPT, add function callback support and other functionalities
- optimize the logic of LLM interaction based on ChatGPT
- abstract interface for other LLMs and implement it

This may take some time.

I don't want to extend based on `LLM` or `gptel`, yes they are excellent, but their implementations are a bit too coupled for me.

Welcome to try out the `chat` branch, and hope to get more suggestions, especially on interaction logic design. Thanks.

**Comment by hwiorn** [comment]
I thought just adding new LLM(e.g: ellama) backend into it is enough.

> I don't want to extend based on LLM or gptel, yes they are excellent, but their implementations are a bit too coupled for me.

I agree. But it seems like it would take a lot of work and time.

 > Welcome to try out the chat branch, and hope to get more suggestions, especially on interaction logic design. Thanks.

Okay, I'll check it out.
