### ISSUE TITLE
`invalid-function gt-log`

### ISSUE THREAD

**Issue by liar666** [lorniu/go-translate#79]
Hi,

I've just upgraded my doomemacs and now I get `invalid-function gt-log` when calling `gt-do-translate`

**Comment by gynamics** [comment]
I got this error too, it seems to be a compilation problem when you have a clean installation. `gt-log` is a macro, it may be applied inproperly somewhere, which caused the compiler recognize it as a function. If you want to get it work, simply run ``byte-force-recompile` on your package.

**Comment by lorniu** [comment]
Updated.
