### ISSUE TITLE
Switching language pair without input? 

### ISSUE THREAD

**Issue by okomestudio** [lorniu/go-translate#80]
This seems to be a new behavior introduced by the new release. 

It used to be that I can switch the language pair (defined in `gt-langs`) any time using `C-p` and `C-n` when the minibuffer shows the `[lang1 > lang2] Text:` prompt even when there is no characters are typed in.

Now, it seems that there is a language auto-detection layer, which tries to infer the source language from the text entered at prompt. This doesn't always work as intended, since some languages partially share the character set and the auto-detection appears to struggle when `gt-langs` doesn't have a language that it thinks is in input text.

For example, this happens when I type in Japanese Kanji, which `go-translate` probably thinks is in Chinese but cannot find the proper language pair since I don't have any Chinese defined in my `gt-langs`. 

Is there any way to bring back the old behavior, i.e., switching a pair from `gt-langs` without any text entered at the prompt?

**Comment by lorniu** [comment]
Force switch with `C-u` prefix, that is `C-u C-p` or `C-u C-n`.

**Comment by lorniu** [comment]
> switching a pair from gt-langs without any text entered at the prompt?

See the latest commit.

**Comment by okomestudio** [comment]
Perfect. I've updated the package to the current master with the patch, and now I can confirm that both using the `C-u` prefix and switching without any text at prompt. 

Thank you very much for the very fast response and the fix! I appreciate it.
